### ISSUE TITLE
设置favicon

### ISSUE THREAD

**Issue by BorisYang326** [eatradish/saki.li#4]
开发者您好！想请问关于如何设置favicon的问题

> ### 关于图标
> 把你的 `favicon.ico` 复制到 `$BLOG/source` 或 `$BLOG/themes/saki.li/source` 即可

我已经尝试将favicon文件放到这两个目录下然后进行 `hexo clean && hexo g & hexo d `。但并没有生效？是否需要在`themes/saki.li/_config.yml` 进行相应的设置呢？

**Comment by eatradish** [comment]
目前使用 `favicon.png` ，我忘记更改 README 了，把你的 `favicon.png` 复制到两个目录之一即可。不需要设置 `_config.yml` 。（要注意的是文件名和扩展名必须一致）

当然，这里我在想考虑把它抽象出来，让你们自己设置图标的文件名

**Comment by BorisYang326** [comment]
谢谢您的回复！我很喜爱您所制作的Hexo主题。但我现在发现没有Tags 和 Category 功能。您是否考虑愿意增加这两个页面和对应的ejs文件。如果可以的话我愿意以30￥每个功能支持您！
2020年2月6日 下午8:35，Mag Mell <notifications@github.com<mailto:notifications@github.com>> 写道：


目前使用 favicon.png ，我忘记更改 README 了，把你的 favicon.png 复制到两个目录之一即可。不需要设置 _config.yml 。（要注意的是文件名和扩展名必须一致）

当然，这里我在想考虑把它抽象出来，让你们自己设置图标的文件名

**Comment by eatradish** [comment]
这两天也许会增加这两个页面
