### ISSUE TITLE
正文标题中带有符号会导致标题不正常显示

### ISSUE THREAD

**Issue by KagurazakaX** [eatradish/saki.li#8]
比如说一个四级标题
```#### 归档（一）```

在正文中会显示成
\#\#\#\# 归档（一）

但是在默认的 landscape 主题中可以显示为
#### 归档（一）

不论是半角还是全角都会如此，怀疑不仅是符号，可能一部分其他的 Unicode 字符也会造成这样的问题

**Comment by eatradish** [comment]
这里并没有复现这个问题，我用的是 Hexo 默认的 Markdown 渲染引擎，您是否更换了 Hexo 的 Markdown 渲染引擎？

**Comment by KagurazakaX** [comment]
我用的是默认的渲染引擎。
最近又试了一下发现正常了，并且也无法复现
怀疑和 node 有关系（因为似乎是最近更新了 node 之后就没有这个问题了
