### ISSUE TITLE
在主页和归档按钮来回点击的时候，页面会移动

### ISSUE THREAD

**Issue by MrSiz** [eatradish/saki.li#9]
+ 点击`归档`时, 页面右移
+ 点击`主页`时, 页面左移

`归档`和`关于`按钮来回点击时，不会出现该现象。使用的是谷歌浏览器

**Comment by eatradish** [comment]
Chromium Version 80.0.3987.149 (Developer Build) AOSC OS (64-bit) 这里没有复现这个问题。请问是什么版本，什么平台呢？

**Comment by MrSiz** [comment]
```
版本 81.0.4044.113（正式版本） （64 位） 
```
我试了点击您的博客，在`归档`和`关于`来回点击时，会出现我所说的现象。

**Comment by eatradish** [comment]
> ```
> 版本 81.0.4044.113（正式版本） （64 位） 
> ```
> 
> 我试了点击您的博客，在`归档`和`关于`来回点击时，会出现我所说的现象。

能录个视频看看是什么情况吗？我问了好几个人说没有复现这个问题

**Comment by eatradish** [comment]
看到了，问题复现

**Comment by eatradish** [comment]
问题在于归档的内容不够长（没有进度条）而首页内容长有进度条，这进度条的显示导致了两个页面的不对齐

解决方案我得想想

**Comment by eatradish** [comment]
@MrSiz 试试最新的 commit 吧

**Comment by MrSiz** [comment]
好的
